language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t siriusda2/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true siriusda2/react-test-app npm run test

after_success:
  - docker build -t siriusda2/docker-frontend ./frontend
  - docker build -t siriusda2/docker-backend ./backend
  - docker build -t siriusda2/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push siriusda2/docker-frontend
  - docker push siriusda2/docker-backend
  - docker push siriusda2/docker-nginx

deploy:
  # Elastic Beanstalk
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  # S3
  bucket_name: elasticbeanstalk-us-east-1-084434575446
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY

